<a href="https://colab.research.google.com/github/Mridul027M/machine-learning/blob/main/assignment1_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

part 1

In [4]:
import numpy as np
arr=np.zeros(10)
print(arr)
arr1=np.ones(10)
print(arr1)
arr2=np.ones(10)*5
print(arr2)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [5]:
import numpy as np
array=np.arange(10,50,2)

print(array) 

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [21]:
import numpy as np
from numpy import random

x = np.random.rand(3,3)

print(x)
np.savetxt('4.txt',x)
res=np.loadtxt('4.txt')
print(res)


[[0.84048435 0.12143363 0.75283211]
 [0.98234024 0.67130926 0.40492214]
 [0.5435984  0.42666143 0.54416946]]
[[0.84048435 0.12143363 0.75283211]
 [0.98234024 0.67130926 0.40492214]
 [0.5435984  0.42666143 0.54416946]]


part 2


In [48]:
import numpy as np
import PIL

img_data = PIL.Image.open('Desktop/panda_image.jpg' )
img_arr = np.array(img_data) 
print(img_arr)

FileNotFoundError: ignored

In [32]:
import pandas as pd
from datetime import date
current = pd.to_datetime(str(date.today()), format='%Y-%m-%d')
print(current)

2021-08-08 00:00:00


part 3

In [44]:
from datetime import date

def calculate_age(dtob):
    today = date.today()
    return today.year - dtob.year - ((today.month, today.day) < (dtob.month, dtob.day))
print("year:")
year=int(input())
print("month:")
month=int(input())
print("day:")
day=int(input())
print("your age is-",calculate_age(date(year,month,day)))


year:
2000
month:
9
day:
8
your age is- 20
