<a href="https://colab.research.google.com/github/Mridul027M/machine-learning/blob/main/assignment1_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

part 1

In [ ]:
import numpy as np
arr=np.zeros(10)
print(arr)
arr1=np.ones(10)
print(arr1)
arr2=np.ones(10)*5
print(arr2)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
import numpy as np
array=np.arange(10,50,2)

print(array) 

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
import numpy as np
from numpy import random

x = np.random.rand(5,6)

print(x)
np.savetxt('/content/p1q4.txt',x)
res=np.loadtxt('/content/p1q4.txt')
print("loaded from the file:   ")
print(res)


[[0.48506781 0.84066939 0.22437791 0.71127457 0.08693806 0.73041901]
 [0.80669192 0.2065203  0.35808002 0.12054635 0.99049881 0.0571104 ]
 [0.21815649 0.04204094 0.67865165 0.40087861 0.60033341 0.42803843]
 [0.50000485 0.27982269 0.82934337 0.09820821 0.20323658 0.76462087]
 [0.95396211 0.30738605 0.68629525 0.74106519 0.37291406 0.65904787]]
loaded from the file:   
[[0.48506781 0.84066939 0.22437791 0.71127457 0.08693806 0.73041901]
 [0.80669192 0.2065203  0.35808002 0.12054635 0.99049881 0.0571104 ]
 [0.21815649 0.04204094 0.67865165 0.40087861 0.60033341 0.42803843]
 [0.50000485 0.27982269 0.82934337 0.09820821 0.20323658 0.76462087]
 [0.95396211 0.30738605 0.68629525 0.74106519 0.37291406 0.65904787]]


part 2


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.image as img

imMatrix = img.imread('/content/panda_image.jpg')

imMatrix = imageMatrix.reshape(imMatrix.shape[0],imMatrix.shape[1]*imMatrix.shape[2])

df = pd.DataFrame(imMatrix)


df.to_csv('csv_example',index=False)


last_row = len(df)
print(last_row)
print(len(df.columns))
new_df = pd.read_csv('csv_example',nrows=last_row-1,usecols=range(len(df.columns)-1))

print(new_df)

1500
3000
        0    1    2    3    4    5  ...  2993  2994  2995  2996  2997  2998
0      50  111    0   46  105    0  ...     9    37    77     4    37    81
1      44  106    0   42  102    2  ...     0    24    63     0    29    72
2      38   99    6   33   92    0  ...     6    21    61     1    21    63
3      35   98    9   26   88    0  ...     8    33    75    12    31    77
4      45  108    4   40  103    0  ...     0    48    90    14    55   103
...   ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...   ...   ...
1494  107  161   49   96  142   34  ...   110   180   185    85   133   148
1495  109  160   57   88  133   32  ...    71   130   136    46   102   124
1496  143  189   99  113  153   65  ...     4    82    79     2    86    94
1497  188  223  165  171  205  145  ...     7    89    74     7    93    85
1498  215  236  217  214  235  216  ...    25    95    76    18    86    76

[1499 rows x 2999 columns]


In [ ]:
import pandas as pd
from datetime import date
current = pd.to_datetime(date.today()).date()
print(current)

2021-08-09


part 3

In [ ]:
from datetime import date

def calculate_age(dtob):
    today = date.today()
    return today.year - dtob.year - ((today.month, today.day) < (dtob.month, dtob.day))
print()
year=int(input("year:"))
print()
month=int(input("month:"))
print()
day=int(input("day:"))
print("your age is-",calculate_age(date(year,month,day)),"years")



year:2000

month:9

day:8
your age is- 20 years
