<a href="https://colab.research.google.com/github/Mridul027M/machine-learning/blob/main/k_medoid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import matplotlib.pyplot as plt
import numpy as np
import random
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import math
import seaborn as sns
from sklearn.model_selection import KFold
from sklearn.preprocessing import MinMaxScaler
iris = sns.load_dataset("iris")
data2=iris.to_numpy()

y=np.array(iris['species'])
for i in range(len(y)):
    if(y[i]=="setosa"):
        y[i]=0
    elif(y[i]=="versicolor"):   
        y[i]=1
    else:
        y[i]=2
data2=np.delete(data2,4,1)        
data=data2

print(len(y))
data=np.insert(data,4,y,axis=1)
print(data)
cluster=[0,0,0]
for i in range(0,3):
    a=random.randint(0,149)
    cluster[i]=data2[a]
    

def dist(p1,p2):
    distance = math.sqrt( ((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2) )
    return distance

def medoid(data2,y,cluster,x):
    for i in range(len(data2)):
        smallest=100000
        y_smallest=[]
        
        for j in range(0,3):
            dis=dist(data2[i],cluster[j])
            if dis<smallest and dis!=0:
                smallest=dis
                y_smallest=y[i]
                 
   
        x[i]=y_smallest
    for j in range(0,3):
        smallest=10000
        clus_update=[]
        for i in range(0,150):
            if y[i]==j:
                dis=dist(data2[i],cluster[j])
                if dis<smallest and dis!=0:
                    smallest=dis
                    clus_update=data2[i]
        cluster[j]=clus_update  
    


x=np.zeros(150)
  
for k in range(0,100):
    if(k>1):
        same=1
        for i in range(0,150):
            if x[i]!=y[i]:
                same=0*same
        if(same==0):
            break

        else:
            medoid(data2,y,cluster,x)
    else:
        medoid(data2,y,cluster,x)
        
        
silhoutte=silhouette_score(data2,y)      
print(silhoutte)

kmeans = KMeans(n_clusters=3, random_state=0).fit(data)
silhouette = silhouette_score(data, kmeans.labels_)
print(silhouette)

150
[[5.1 3.5 1.4 0.2 0]
 [4.9 3.0 1.4 0.2 0]
 [4.7 3.2 1.3 0.2 0]
 [4.6 3.1 1.5 0.2 0]
 [5.0 3.6 1.4 0.2 0]
 [5.4 3.9 1.7 0.4 0]
 [4.6 3.4 1.4 0.3 0]
 [5.0 3.4 1.5 0.2 0]
 [4.4 2.9 1.4 0.2 0]
 [4.9 3.1 1.5 0.1 0]
 [5.4 3.7 1.5 0.2 0]
 [4.8 3.4 1.6 0.2 0]
 [4.8 3.0 1.4 0.1 0]
 [4.3 3.0 1.1 0.1 0]
 [5.8 4.0 1.2 0.2 0]
 [5.7 4.4 1.5 0.4 0]
 [5.4 3.9 1.3 0.4 0]
 [5.1 3.5 1.4 0.3 0]
 [5.7 3.8 1.7 0.3 0]
 [5.1 3.8 1.5 0.3 0]
 [5.4 3.4 1.7 0.2 0]
 [5.1 3.7 1.5 0.4 0]
 [4.6 3.6 1.0 0.2 0]
 [5.1 3.3 1.7 0.5 0]
 [4.8 3.4 1.9 0.2 0]
 [5.0 3.0 1.6 0.2 0]
 [5.0 3.4 1.6 0.4 0]
 [5.2 3.5 1.5 0.2 0]
 [5.2 3.4 1.4 0.2 0]
 [4.7 3.2 1.6 0.2 0]
 [4.8 3.1 1.6 0.2 0]
 [5.4 3.4 1.5 0.4 0]
 [5.2 4.1 1.5 0.1 0]
 [5.5 4.2 1.4 0.2 0]
 [4.9 3.1 1.5 0.2 0]
 [5.0 3.2 1.2 0.2 0]
 [5.5 3.5 1.3 0.2 0]
 [4.9 3.6 1.4 0.1 0]
 [4.4 3.0 1.3 0.2 0]
 [5.1 3.4 1.5 0.2 0]
 [5.0 3.5 1.3 0.3 0]
 [4.5 2.3 1.3 0.3 0]
 [4.4 3.2 1.3 0.2 0]
 [5.0 3.5 1.6 0.6 0]
 [5.1 3.8 1.9 0.4 0]
 [4.8 3.0 1.4 0.3 0]
 [5.1 3.8 1.6 0.2 0]
 [4.6 3.2